apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderburger
  labels:
    app: orderburger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderburger
  template:
    metadata:
      labels:
        app: orderburger
    spec:
      containers:
        - name: orderburger
          image: username/orderburger:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
